/**
 * Concept vocabulary for decoding embeddings back to human-readable terms.
 * Uses pre-computed embeddings from src/data/vocabulary.json (generated by
 * scripts/generate-vocabulary-embeddings.mjs using all-MiniLM-L6-v2).
 */

import type { ConceptEntry } from './schemas';
import { cosineSimilarity } from './similarity';

let cachedVocabulary: ConceptEntry[] | null = null;

/**
 * Load the pre-computed vocabulary.
 * In browser context, imports the JSON at build time via Vite/Astro.
 */
export function loadVocabulary(preloaded?: ConceptEntry[]): ConceptEntry[] {
  if (cachedVocabulary) return cachedVocabulary;
  if (preloaded) {
    cachedVocabulary = preloaded;
    return cachedVocabulary;
  }
  return [];
}

/**
 * Decode an embedding vector to the top-K closest concepts from the vocabulary.
 */
/**
 * Decode an embedding vector to the closest concepts from the vocabulary.
 * Uses adaptive score-gap detection: returns top concepts until a significant
 * drop in cosine similarity is detected, rather than a fixed count.
 */
export function decodeConcepts(
  embedding: number[],
  vocabulary: ConceptEntry[],
  options?: {
    maxK?: number;
    minK?: number;
    gapMultiplier?: number;
  },
): string[] {
  const maxK = options?.maxK ?? 12;
  const minK = options?.minK ?? 3;
  const gapMultiplier = options?.gapMultiplier ?? 1.5;

  const scored = vocabulary
    .map((entry) => ({
      term: entry.term,
      score: cosineSimilarity(embedding, entry.embedding),
    }))
    .sort((a, b) => b.score - a.score)
    .slice(0, maxK);

  // If pool is smaller than minK, return all
  if (scored.length <= minK) {
    return scored.map((r) => r.term);
  }

  // Compute gaps between consecutive scores
  const gaps: number[] = [];
  for (let i = 0; i < scored.length - 1; i++) {
    gaps.push(scored[i].score - scored[i + 1].score);
  }

  // Mean gap as baseline
  const meanGap = gaps.reduce((sum, g) => sum + g, 0) / gaps.length;
  const threshold = meanGap * gapMultiplier;

  // Scan from minK onward — find first significant gap
  let cutAt = scored.length;
  for (let i = minK - 1; i < gaps.length; i++) {
    if (gaps[i] > threshold) {
      cutAt = i + 1;
      break;
    }
  }

  return scored.slice(0, cutAt).map((r) => r.term);
}

/**
 * Capitalize a term: "anomaly detection" → "Anomaly Detection"
 */
function titleCase(term: string): string {
  return term.split(' ').map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
}

/**
 * Pick the N most distinctive concepts — prefer multi-word terms (more specific),
 * then longer single-word terms, and only from the dictionary source when possible.
 */
function pickDistinctive(concepts: string[], n: number): string[] {
  return concepts
    .slice()
    .sort((a, b) => {
      const aWords = a.split(' ').length;
      const bWords = b.split(' ').length;
      if (bWords !== aWords) return bWords - aWords;
      return b.length - a.length;
    })
    .slice(0, n);
}

/**
 * Generate a suggested title and description for an offspring
 * based on its decoded concepts and parent ideas.
 */
export function generateOffspringText(
  concepts: string[],
  parentA?: { title: string; description: string },
  parentB?: { title: string; description: string },
): { title: string; description: string } {
  const top = pickDistinctive(concepts, 3);
  const rest = concepts.filter((c) => !top.includes(c));

  // Title: "Concept A for Concept B" or "Concept A × Concept B"
  let title: string;
  if (top.length >= 2) {
    title = `${titleCase(top[0])} for ${titleCase(top[1])}`;
  } else if (top.length === 1) {
    title = titleCase(top[0]);
  } else {
    title = 'Untitled Offspring';
  }

  // Description: a readable sentence about what this offspring explores
  const parts: string[] = [];

  if (parentA && parentB) {
    parts.push(`Hybrid idea combining aspects of "${parentA.title}" and "${parentB.title}".`);
  }

  // Main sentence about what the idea explores
  if (top.length >= 2) {
    const topFormatted = top.map(titleCase);
    parts.push(
      `Explores ${topFormatted.slice(0, -1).join(', ')} and ${topFormatted[topFormatted.length - 1]}.`,
    );
  }

  // Mention remaining concepts as related areas
  if (rest.length > 0) {
    parts.push(`Related areas: ${rest.join(', ')}.`);
  }

  return { title, description: parts.join(' ') };
}

/**
 * Reset the cached vocabulary (useful when ideas change).
 */
export function resetVocabularyCache(): void {
  cachedVocabulary = null;
}
